import React, { useState } from 'react';
import { chatAPI } from '../services/api';

export default function ResumeRewriter() {
  const [inputText, setInputText] = useState('')
  const [results, setResults] = useState([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [copied, setCopied] = useState(null)

  const handleImprove = async () => {
    const bullets = inputText.split('\n').map(l => l.trim()).filter(l => l.length > 4);
    if (bullets.length === 0) {
      setError('Enter at least one bullet point (one per line).');
      return;
    }
    setLoading(true);
    setError('');
    setResults([]);

    try {
      const response = await chatAPI.rewriteBullets({
        bullet_points: bullets
      });

      // Response now contains just the improved strings
      const rewrittenBullets = response.data.rewritten_bullets || [];
      
      // Transform the response to match the expected format
      const transformedResults = rewrittenBullets.map((improved, index) => ({
        original: bullets[index] || '',
        improved: improved,
        changes: ['Enhanced wording', 'Improved clarity', 'Better ATS compatibility'],
        suggestions: ['Consider adding specific numbers', 'Use stronger action verbs', 'Quantify your achievements']
      }));

      setResults(transformedResults);
    } catch (err) {
      console.error('Rewrite failed:', err);
      const errorMsg = err.response?.data?.detail || 'Rewrite failed. Please try again.';
      setError(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = (text, idx) => {
    navigator.clipboard.writeText(text)
    setCopied(idx)
    setTimeout(() => setCopied(null), 1500)
  }

  const handleDownloadResume = () => {
    if (results.length === 0) return;

    // Create formatted resume text
    const resumeContent = results
      .map(r => `• ${r.improved}`)
      .join('\n\n');

    const fullContent = `IMPROVED RESUME BULLETS
Generated by AI Resume Analyzer
================================

${resumeContent}

================================
Tips for implementation:
- Replace your current bullet points with these improved versions
- Maintain consistent formatting throughout your resume
- Ensure each bullet follows the CAR format (Challenge-Action-Result)
- Add metrics and numbers where possible
- Use action verbs at the beginning of each bullet point
`;

    // Create blob and download
    const element = document.createElement('a');
    element.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(fullContent));
    element.setAttribute('download', 'improved_resume_bullets.txt');
    element.style.display = 'none';
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 pt-32 pb-12 px-6">
      <div className="max-w-5xl mx-auto">
        {/* Header */}
        <div className="mb-8">
          <h1 className="text-4xl font-bold mb-2">AI Resume Rewriter</h1>
          <p className="text-slate-400">Paste your bullet points (one per line) and get AI-improved versions</p>
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400">{error}</div>
        )}

        {/* Input */}
        <div className="dashboard-card mb-6">
          <label className="block text-lg font-semibold mb-3">Your Bullet Points</label>
          <textarea value={inputText} onChange={(e) => setInputText(e.target.value)}
            placeholder={"Worked on ML project for customer segmentation\nResponsible for managing a team and did code reviews\nHelped improve the website performance"}
            className="w-full min-h-48 bg-white/5 border border-white/10 rounded-xl px-4 py-3 text-white placeholder-slate-500 focus:outline-none focus:bg-white/10 focus:border-cyan-500/50 transition-all resize-none"
          />
          <div className="flex justify-between items-center mt-3">
            <span className="text-xs text-slate-500">{inputText.split('\n').filter(l => l.trim().length > 4).length} bullet(s) detected</span>
            <button onClick={handleImprove} disabled={loading || !inputText.trim()}
              className="btn-primary px-8 py-2 disabled:opacity-50 disabled:cursor-not-allowed">
              {loading ? 'Improving…' : '✨ Improve with AI'}
            </button>
          </div>
        </div>

        {/* Results */}
        {results.length > 0 && (
          <div className="space-y-6 animate-fade-in">
            <div className="flex justify-between items-center">
              <h2 className="text-2xl font-bold">Results ({results.length})</h2>
              <button onClick={handleDownloadResume}
                className="btn-primary px-6 py-2 text-sm flex items-center gap-2">
                ⬇️ Download Resume
              </button>
            </div>
            {results.map((r, i) => (
              <div key={i} className="dashboard-card">
                {/* Original */}
                <div className="mb-4">
                  <p className="text-xs font-semibold text-slate-500 mb-1">ORIGINAL</p>
                  <p className="text-slate-400 bg-white/5 p-3 rounded-lg text-sm">{r.original}</p>
                </div>
                {/* Improved */}
                <div className="mb-4">
                  <p className="text-xs font-semibold text-green-400 mb-1">IMPROVED</p>
                  <p className="text-white bg-gradient-to-r from-cyan-500/10 to-blue-500/10 border border-cyan-500/20 p-3 rounded-lg text-sm">{r.improved}</p>
                </div>
                {/* Changes */}
                {r.changes?.length > 0 && (
                  <div className="mb-3">
                    <p className="text-xs font-semibold text-slate-500 mb-1">CHANGES MADE</p>
                    <div className="flex flex-wrap gap-2">
                      {r.changes.map((c, ci) => (
                        <span key={ci} className="px-2 py-1 text-xs rounded-full bg-purple-500/20 text-purple-400 border border-purple-500/30">{c}</span>
                      ))}
                    </div>
                  </div>
                )}
                {/* Suggestions */}
                {r.suggestions?.length > 0 && (
                  <div className="mb-3">
                    <p className="text-xs font-semibold text-slate-500 mb-1">SUGGESTIONS</p>
                    <ul className="space-y-1">
                      {r.suggestions.map((s, si) => (
                        <li key={si} className="flex items-start gap-2 text-sm text-yellow-400">
                          <span>💡</span><span>{s}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
                {/* Copy */}
                <button onClick={() => handleCopy(r.improved, i)}
                  className="btn-secondary text-xs px-4 py-1.5 mt-2">
                  {copied === i ? '✓ Copied!' : '📋 Copy Improved'}
                </button>
              </div>
            ))}
          </div>
        )}

        {/* Tips */}
        <div className="mt-12 dashboard-card">
          <h3 className="text-xl font-semibold mb-6">📚 Writing Tips</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="flex items-start gap-3">
              <span className="text-2xl">🎯</span>
              <div>
                <p className="font-semibold text-white mb-1">Start with Action Verbs</p>
                <p className="text-sm text-slate-400">Led, Architected, Spearheaded, Implemented</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">📊</span>
              <div>
                <p className="font-semibold text-white mb-1">Add Quantifiable Results</p>
                <p className="text-sm text-slate-400">40% improvement, $2M saved, 100K users</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">🔧</span>
              <div>
                <p className="font-semibold text-white mb-1">Highlight Technical Skills</p>
                <p className="text-sm text-slate-400">Mention specific technologies and frameworks</p>
              </div>
            </div>
            <div className="flex items-start gap-3">
              <span className="text-2xl">🌟</span>
              <div>
                <p className="font-semibold text-white mb-1">Show Business Impact</p>
                <p className="text-sm text-slate-400">Explain how your work contributed to goals</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
